###########
# Variables
###########

# Provide full paths for principal variables,
# each without a trailing slash

# Project files distribution root
# Example:
#PRJ = /Users/alex.jordan/APEXCalculusPTX
PRJ = /Users/gretaswanson/Supplement111-112

# PreTeXt distribution root
# Example:
#PTX = /Users/alex.jordan/mathbook
PTX = /Users/gretaswanson/mathbook
